defaultContentLanguage = "ja"
languageCode = "ja"
title = "インフラ勉強会 半年記念イベント"
baseURL = "https://infra-workshop-aa7e9.firebaseapp.com/"
theme = "hugo-theme-massively"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = "UA-113904582-4"
    disqus = "hugo-massively"

[languages]
[languages.ja]
  languageName = "Japanese"
